spring:
  application:
    name: kg-free-places-monitor
  mail:
    host: ${MAIL_HOST:smtp-relay.brevo.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:997d43001@smtp-brevo.com}
    password: ${MAIL_PASSWORD:qZK217aXyLAnbrMW}
    properties:
      mail:
        smtp:
        auth: true
        starttls:
          enable: true
monitor:
  api:
    url: https://newkg.uslugi.io/lv/api/free-places
    reception: jasla
    timeout-ms: 5000
    retry:
      max-attempts: 3
      backoff-ms: 1000
  schedule:
    cron: "0 */5 * * * *"  # every 5 minutes
  email:
    from: akokoshqn@gmail.com
    to: akokoshqn@gmail.com
    subject: "[KG] Free places status changed"

logging:
  level:
    root: INFO
    io.services.monitor: INFO